name: Build and Release

# -------------------------------------------------------------
# Trigger workflow on any Git tag starting with "v" (e.g., v1.0.0)
# -------------------------------------------------------------
on:
  push:
    tags:
      - "v*"

# =============================================================
# Jobs definition
# =============================================================

jobs:
  # ---------------------------------------------------------
  # Build the Linux binary using PyInstaller
  # ---------------------------------------------------------
  build:
    name: Build Linux binary
    runs-on: ubuntu-latest

    steps:
      # ---------------------------------------------------
      # Checkout the repository at the tag that triggered this workflow
      # ---------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch full history so tags are available

      # ---------------------------------------------------
      # Set up Python environment (version 3.11)
      # ---------------------------------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # ---------------------------------------------------
      # Install package in editable mode + PyInstaller
      # ---------------------------------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .           # Install your notes package
          pip install pyinstaller    # Required to build the binary

      # ---------------------------------------------------
      # Build a single‑file Linux executable from run_notes.py
      # ---------------------------------------------------
      - name: Build binary with PyInstaller
        run: |
          # The back‑slashes must be the very last character on each line
          pyinstaller \
            --onefile \
            --collect-all notes \
            --collect-all rich \
            run_notes.py \
            --name notes

      # ---------------------------------------------------
      # Make binary executable and package it into a zip
      # ---------------------------------------------------
      - name: Package the binary
        shell: bash
        run: |
          chmod +x dist/notes            # Ensure executable permission
          zip notes-linux.zip dist/notes

      # ---------------------------------------------------
      # Upload the zip as a workflow artifact
      # ---------------------------------------------------
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: notes-linux
          path: notes-linux.zip

  # ---------------------------------------------------------
  # Create a GitHub Release and attach the Linux artifact
  # ---------------------------------------------------------
  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to create release and attach assets

    steps:
      # ---------------------------------------------------
      # Download the artifact produced by the build job
      # ---------------------------------------------------
      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: notes-linux
          path: ./artifacts

      # ---------------------------------------------------
      # Publish a Release and attach the zip file
      # ---------------------------------------------------
      - name: Create Release and attach binary
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} # Release uses the tag name
          name: Release ${{ github.ref_name }}
          body: |
            Linux‑only release – a single‑file executable built with PyInstaller.
            Download `notes-linux.zip`, unzip, and run `./notes` (or move it to a folder on your $PATH).
          files: ./artifacts/notes-linux.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required to authenticate with GitHub
